source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SDWebImagePromiseKit_Example' do
  pod 'SDWebImagePromiseKit', :path => '../'
end

target 'SDWebImagePromiseKit_Tests' do
  pod 'SDWebImagePromiseKit', :path => '../'

  
end
